sudo: required
dist: bionic
language: python
python:
  - "3.6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U python-dotenv
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
install:
  - pip3 install -r requirements-dev.txt
  - pip3 install -r requirements.txt
script: ./bin/test
after_success:
  - ./bin/coverage
env:
  global:
    - CXX=g++-4.8
    - NODE_ENV=development
branches:
  - release
  - test